/*
 * File: app/store/CustomerStore.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.0.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.0.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.CustomerStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.CustomerModel',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CustomerStore',
            autoLoad: true,
            model: 'MyApp.model.CustomerModel',
            proxy: {
                type: 'rest',
                url: 'http://localhost:8080/EMSDataSetResource/',
                reader: {
                    type: 'json',
                    rootProperty: 'result'
                }
            }
        }, cfg)]);
    }
});