/*
 * File: app/model/CustomerModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.CustomerModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'CUST_NO'
        },
        {
            name: 'CUSTOMER'
        },
        {
            name: 'CONTACT_FIRST'
        },
        {
            name: 'CONTACT_LAST'
        },
        {
            name: 'PHONE_NO'
        },
        {
            name: 'ADDRESS_LINE1'
        },
        {
            name: 'CITY'
        },
        {
            name: 'STATE_PROVINCE'
        },
        {
            name: 'COUNTRY'
        },
        {
            name: 'POSTAL_CODE'
        }
    ]

});