/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mypanel',

    requires: [
        'MyApp.view.MyPanelViewModel',
        'Ext.grid.Grid',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Text'
    ],

    viewModel: {
        type: 'mypanel'
    },
    title: 'My Panel',

    items: [
        {
            xtype: 'grid',
            height: '100%',
            width: '100%',
            store: 'CustomerStore',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 89,
                    dataIndex: 'CUST_NO',
                    text: 'CUST_ID'
                },
                {
                    xtype: 'textcolumn',
                    width: 130,
                    dataIndex: 'CUSTOMER',
                    text: 'NAME'
                },
                {
                    xtype: 'textcolumn',
                    height: 37,
                    width: 103,
                    dataIndex: 'PHONE_NO',
                    text: 'PHONE_NO'
                }
            ]
        }
    ]

});